// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: catalog.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const assignProductToCollection = `-- name: AssignProductToCollection :exec
INSERT INTO collection_products (collection_id, product_id)
SELECT $3, $4
WHERE EXISTS (
  SELECT 1 FROM collections c
  WHERE c.id = $3 AND c.tenant_id = $1 AND c.region_id = $2
)
AND EXISTS (
  SELECT 1 FROM products p
  WHERE p.id = $4 AND p.tenant_id = $1 AND p.region_id = $2
)
ON CONFLICT (collection_id, product_id) DO NOTHING
`

type AssignProductToCollectionParams struct {
	TenantID     string
	RegionID     string
	CollectionID string
	ProductID    string
}

func (q *Queries) AssignProductToCollection(ctx context.Context, arg AssignProductToCollectionParams) error {
	_, err := q.db.ExecContext(ctx, assignProductToCollection,
		arg.TenantID,
		arg.RegionID,
		arg.CollectionID,
		arg.ProductID,
	)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, tenant_id, region_id, sku, name, currency, price_cents, created_at, updated_at
FROM products
WHERE id = $1 AND tenant_id = $2
`

type GetProductByIDParams struct {
	ID       string
	TenantID string
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, arg.ID, arg.TenantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Sku,
		&i.Name,
		&i.Currency,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (id, tenant_id, region_id, name, slug, parent_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, tenant_id, region_id, name, slug, parent_id, created_at, updated_at
`

type InsertCategoryParams struct {
	ID       string
	TenantID string
	RegionID string
	Name     string
	Slug     string
	ParentID sql.NullString
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, insertCategory,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCollection = `-- name: InsertCollection :one
INSERT INTO collections (id, tenant_id, region_id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, tenant_id, region_id, name, slug, created_at, updated_at
`

type InsertCollectionParams struct {
	ID       string
	TenantID string
	RegionID string
	Name     string
	Slug     string
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, insertCollection,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.Name,
		arg.Slug,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductMedia = `-- name: InsertProductMedia :one
INSERT INTO product_media (id, tenant_id, region_id, product_id, url, media_type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, tenant_id, region_id, product_id, url, media_type, created_at, updated_at
`

type InsertProductMediaParams struct {
	ID        string
	TenantID  string
	RegionID  string
	ProductID string
	Url       string
	MediaType string
}

func (q *Queries) InsertProductMedia(ctx context.Context, arg InsertProductMediaParams) (ProductMedium, error) {
	row := q.db.QueryRowContext(ctx, insertProductMedia,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.ProductID,
		arg.Url,
		arg.MediaType,
	)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.ProductID,
		&i.Url,
		&i.MediaType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByTenantRegion = `-- name: ListCategoriesByTenantRegion :many
SELECT id, tenant_id, region_id, name, slug, parent_id, created_at, updated_at
FROM categories
WHERE tenant_id = $1 AND region_id = $2
ORDER BY created_at DESC
`

type ListCategoriesByTenantRegionParams struct {
	TenantID string
	RegionID string
}

func (q *Queries) ListCategoriesByTenantRegion(ctx context.Context, arg ListCategoriesByTenantRegionParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByTenantRegion, arg.TenantID, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByTenantRegion = `-- name: ListCollectionsByTenantRegion :many
SELECT id, tenant_id, region_id, name, slug, created_at, updated_at
FROM collections
WHERE tenant_id = $1 AND region_id = $2
ORDER BY created_at DESC
`

type ListCollectionsByTenantRegionParams struct {
	TenantID string
	RegionID string
}

func (q *Queries) ListCollectionsByTenantRegion(ctx context.Context, arg ListCollectionsByTenantRegionParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsByTenantRegion, arg.TenantID, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductMediaByProduct = `-- name: ListProductMediaByProduct :many
SELECT id, tenant_id, region_id, product_id, url, media_type, created_at, updated_at
FROM product_media
WHERE tenant_id = $1 AND region_id = $2 AND product_id = $3
ORDER BY created_at DESC
`

type ListProductMediaByProductParams struct {
	TenantID  string
	RegionID  string
	ProductID string
}

func (q *Queries) ListProductMediaByProduct(ctx context.Context, arg ListProductMediaByProductParams) ([]ProductMedium, error) {
	rows, err := q.db.QueryContext(ctx, listProductMediaByProduct, arg.TenantID, arg.RegionID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMedium
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.ProductID,
			&i.Url,
			&i.MediaType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsByProduct = `-- name: ListProductVariantsByProduct :many
SELECT id, tenant_id, region_id, product_id, sku, name, price_cents, currency, created_at, updated_at
FROM product_variants
WHERE tenant_id = $1
  AND region_id = $2
  AND product_id = $3
ORDER BY created_at DESC
`

type ListProductVariantsByProductParams struct {
	TenantID  string
	RegionID  string
	ProductID string
}

func (q *Queries) ListProductVariantsByProduct(ctx context.Context, arg ListProductVariantsByProductParams) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariantsByProduct, arg.TenantID, arg.RegionID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByTenantRegion = `-- name: ListProductsByTenantRegion :many
SELECT id, tenant_id, region_id, sku, name, currency, price_cents, created_at, updated_at
FROM products
WHERE tenant_id = $1
  AND ($2::text = '' OR region_id = $2)
  AND ($3::text = '' OR sku = $3)
  AND ($4::timestamptz IS NULL OR created_at < $4)
ORDER BY created_at DESC
LIMIT $5
`

type ListProductsByTenantRegionParams struct {
	TenantID string
	Column2  string
	Column3  string
	Column4  time.Time
	Limit    int32
}

func (q *Queries) ListProductsByTenantRegion(ctx context.Context, arg ListProductsByTenantRegionParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByTenantRegion,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.Sku,
			&i.Name,
			&i.Currency,
			&i.PriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skuExistsInTenantRegion = `-- name: SkuExistsInTenantRegion :one
SELECT EXISTS (
  SELECT 1 FROM products p
  WHERE p.tenant_id = $1 AND p.region_id = $2 AND p.sku = $3
  UNION ALL
  SELECT 1 FROM product_variants pv
  WHERE pv.tenant_id = $1 AND pv.region_id = $2 AND pv.sku = $3
    AND ($4::text = '' OR pv.id <> $4)
)
`

type SkuExistsInTenantRegionParams struct {
	TenantID string
	RegionID string
	Sku      string
	Column4  string
}

func (q *Queries) SkuExistsInTenantRegion(ctx context.Context, arg SkuExistsInTenantRegionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, skuExistsInTenantRegion,
		arg.TenantID,
		arg.RegionID,
		arg.Sku,
		arg.Column4,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
  id, tenant_id, region_id, sku, name, currency, price_cents, created_at, updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  region_id = EXCLUDED.region_id,
  sku = EXCLUDED.sku,
  name = EXCLUDED.name,
  currency = EXCLUDED.currency,
  price_cents = EXCLUDED.price_cents,
  updated_at = NOW()
RETURNING id, tenant_id, region_id, sku, name, currency, price_cents, created_at, updated_at
`

type UpsertProductParams struct {
	ID         string
	TenantID   string
	RegionID   string
	Sku        string
	Name       string
	Currency   string
	PriceCents int64
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, upsertProduct,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.Sku,
		arg.Name,
		arg.Currency,
		arg.PriceCents,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Sku,
		&i.Name,
		&i.Currency,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductVariant = `-- name: UpsertProductVariant :one
INSERT INTO product_variants (
  id, tenant_id, region_id, product_id, sku, name, price_cents, currency, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  region_id = EXCLUDED.region_id,
  product_id = EXCLUDED.product_id,
  sku = EXCLUDED.sku,
  name = EXCLUDED.name,
  price_cents = EXCLUDED.price_cents,
  currency = EXCLUDED.currency,
  updated_at = NOW()
RETURNING id, tenant_id, region_id, product_id, sku, name, price_cents, currency, created_at, updated_at
`

type UpsertProductVariantParams struct {
	ID         string
	TenantID   string
	RegionID   string
	ProductID  string
	Sku        string
	Name       string
	PriceCents int64
	Currency   string
}

func (q *Queries) UpsertProductVariant(ctx context.Context, arg UpsertProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, upsertProductVariant,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.Currency,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
