// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_types.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const cleanupProductAttributeValuesForProduct = `-- name: CleanupProductAttributeValuesForProduct :exec
DELETE FROM product_attribute_values pav
USING products p
WHERE pav.product_id = p.id
  AND p.id = $1
  AND p.tenant_id = $2
  AND (
    p.product_type_id IS NULL
    OR NOT EXISTS (
      SELECT 1 FROM product_type_attributes pta
      WHERE pta.product_type_id = p.product_type_id
        AND pta.attribute_id = pav.attribute_id
        AND pta.variant_only = false
    )
  )
`

type CleanupProductAttributeValuesForProductParams struct {
	ID       string
	TenantID string
}

func (q *Queries) CleanupProductAttributeValuesForProduct(ctx context.Context, arg CleanupProductAttributeValuesForProductParams) error {
	_, err := q.db.ExecContext(ctx, cleanupProductAttributeValuesForProduct, arg.ID, arg.TenantID)
	return err
}

const cleanupVariantAttributeValuesForProduct = `-- name: CleanupVariantAttributeValuesForProduct :exec
DELETE FROM variant_attribute_values vav
USING product_variants v, products p
WHERE vav.variant_id = v.id
  AND v.product_id = p.id
  AND p.id = $1
  AND p.tenant_id = $2
  AND (
    p.product_type_id IS NULL
    OR NOT EXISTS (
      SELECT 1 FROM product_type_attributes pta
      WHERE pta.product_type_id = p.product_type_id
        AND pta.attribute_id = vav.attribute_id
        AND pta.variant_only = true
    )
  )
`

type CleanupVariantAttributeValuesForProductParams struct {
	ID       string
	TenantID string
}

func (q *Queries) CleanupVariantAttributeValuesForProduct(ctx context.Context, arg CleanupVariantAttributeValuesForProductParams) error {
	_, err := q.db.ExecContext(ctx, cleanupVariantAttributeValuesForProduct, arg.ID, arg.TenantID)
	return err
}

const deleteProductAttributeValuesForUnlinkedAttribute = `-- name: DeleteProductAttributeValuesForUnlinkedAttribute :exec
DELETE FROM product_attribute_values pav
USING products p
WHERE pav.product_id = p.id
  AND p.product_type_id = $1::text
  AND pav.attribute_id = $2
`

type DeleteProductAttributeValuesForUnlinkedAttributeParams struct {
	ProductTypeID string
	AttributeID   string
}

func (q *Queries) DeleteProductAttributeValuesForUnlinkedAttribute(ctx context.Context, arg DeleteProductAttributeValuesForUnlinkedAttributeParams) error {
	_, err := q.db.ExecContext(ctx, deleteProductAttributeValuesForUnlinkedAttribute, arg.ProductTypeID, arg.AttributeID)
	return err
}

const deleteVariantAttributeValuesForUnlinkedAttribute = `-- name: DeleteVariantAttributeValuesForUnlinkedAttribute :exec
DELETE FROM variant_attribute_values vav
USING product_variants v, products p
WHERE vav.variant_id = v.id
  AND v.product_id = p.id
  AND p.product_type_id = $1::text
  AND vav.attribute_id = $2
`

type DeleteVariantAttributeValuesForUnlinkedAttributeParams struct {
	ProductTypeID string
	AttributeID   string
}

func (q *Queries) DeleteVariantAttributeValuesForUnlinkedAttribute(ctx context.Context, arg DeleteVariantAttributeValuesForUnlinkedAttributeParams) error {
	_, err := q.db.ExecContext(ctx, deleteVariantAttributeValuesForUnlinkedAttribute, arg.ProductTypeID, arg.AttributeID)
	return err
}

const getCatalogAttributeByID = `-- name: GetCatalogAttributeByID :one
SELECT id, tenant_id, region_id, name, slug, input_type, unit, allowed_values, created_at, updated_at
FROM catalog_attributes
WHERE id = $1 AND tenant_id = $2 AND region_id = $3
`

type GetCatalogAttributeByIDParams struct {
	ID       string
	TenantID string
	RegionID string
}

func (q *Queries) GetCatalogAttributeByID(ctx context.Context, arg GetCatalogAttributeByIDParams) (CatalogAttribute, error) {
	row := q.db.QueryRowContext(ctx, getCatalogAttributeByID, arg.ID, arg.TenantID, arg.RegionID)
	var i CatalogAttribute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Name,
		&i.Slug,
		&i.InputType,
		&i.Unit,
		&i.AllowedValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductRegionAndType = `-- name: GetProductRegionAndType :one
SELECT region_id, product_type_id FROM products WHERE id = $1 AND tenant_id = $2
`

type GetProductRegionAndTypeParams struct {
	ID       string
	TenantID string
}

type GetProductRegionAndTypeRow struct {
	RegionID      string
	ProductTypeID sql.NullString
}

func (q *Queries) GetProductRegionAndType(ctx context.Context, arg GetProductRegionAndTypeParams) (GetProductRegionAndTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getProductRegionAndType, arg.ID, arg.TenantID)
	var i GetProductRegionAndTypeRow
	err := row.Scan(&i.RegionID, &i.ProductTypeID)
	return i, err
}

const getProductTypeAttributeAssignment = `-- name: GetProductTypeAttributeAssignment :one
SELECT variant_only
FROM product_type_attributes pta
JOIN product_types pt ON pt.id = pta.product_type_id
WHERE pta.product_type_id = $1 AND pta.attribute_id = $2 AND pt.tenant_id = $3 AND pt.region_id = $4
`

type GetProductTypeAttributeAssignmentParams struct {
	ProductTypeID string
	AttributeID   string
	TenantID      string
	RegionID      string
}

func (q *Queries) GetProductTypeAttributeAssignment(ctx context.Context, arg GetProductTypeAttributeAssignmentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getProductTypeAttributeAssignment,
		arg.ProductTypeID,
		arg.AttributeID,
		arg.TenantID,
		arg.RegionID,
	)
	var variant_only bool
	err := row.Scan(&variant_only)
	return variant_only, err
}

const getProductTypeByID = `-- name: GetProductTypeByID :one
SELECT id, tenant_id, region_id, name, slug, created_at, updated_at
FROM product_types
WHERE id = $1 AND tenant_id = $2 AND region_id = $3
`

type GetProductTypeByIDParams struct {
	ID       string
	TenantID string
	RegionID string
}

func (q *Queries) GetProductTypeByID(ctx context.Context, arg GetProductTypeByIDParams) (ProductType, error) {
	row := q.db.QueryRowContext(ctx, getProductTypeByID, arg.ID, arg.TenantID, arg.RegionID)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantProductRegion = `-- name: GetVariantProductRegion :one
SELECT product_id, region_id FROM product_variants WHERE id = $1 AND tenant_id = $2
`

type GetVariantProductRegionParams struct {
	ID       string
	TenantID string
}

type GetVariantProductRegionRow struct {
	ProductID string
	RegionID  string
}

func (q *Queries) GetVariantProductRegion(ctx context.Context, arg GetVariantProductRegionParams) (GetVariantProductRegionRow, error) {
	row := q.db.QueryRowContext(ctx, getVariantProductRegion, arg.ID, arg.TenantID)
	var i GetVariantProductRegionRow
	err := row.Scan(&i.ProductID, &i.RegionID)
	return i, err
}

const insertCatalogAttribute = `-- name: InsertCatalogAttribute :one
INSERT INTO catalog_attributes (id, tenant_id, region_id, name, slug, input_type, unit, allowed_values, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, tenant_id, region_id, name, slug, input_type, unit, allowed_values, created_at, updated_at
`

type InsertCatalogAttributeParams struct {
	ID            string
	TenantID      string
	RegionID      string
	Name          string
	Slug          string
	InputType     string
	Unit          sql.NullString
	AllowedValues pqtype.NullRawMessage
}

func (q *Queries) InsertCatalogAttribute(ctx context.Context, arg InsertCatalogAttributeParams) (CatalogAttribute, error) {
	row := q.db.QueryRowContext(ctx, insertCatalogAttribute,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.Name,
		arg.Slug,
		arg.InputType,
		arg.Unit,
		arg.AllowedValues,
	)
	var i CatalogAttribute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Name,
		&i.Slug,
		&i.InputType,
		&i.Unit,
		&i.AllowedValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductType = `-- name: InsertProductType :one
INSERT INTO product_types (id, tenant_id, region_id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, tenant_id, region_id, name, slug, created_at, updated_at
`

type InsertProductTypeParams struct {
	ID       string
	TenantID string
	RegionID string
	Name     string
	Slug     string
}

func (q *Queries) InsertProductType(ctx context.Context, arg InsertProductTypeParams) (ProductType, error) {
	row := q.db.QueryRowContext(ctx, insertProductType,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.Name,
		arg.Slug,
	)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkAttributeToProductType = `-- name: LinkAttributeToProductType :exec
INSERT INTO product_type_attributes (product_type_id, attribute_id, sort_order, variant_only)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_type_id, attribute_id) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  variant_only = EXCLUDED.variant_only
`

type LinkAttributeToProductTypeParams struct {
	ProductTypeID string
	AttributeID   string
	SortOrder     int32
	VariantOnly   bool
}

func (q *Queries) LinkAttributeToProductType(ctx context.Context, arg LinkAttributeToProductTypeParams) error {
	_, err := q.db.ExecContext(ctx, linkAttributeToProductType,
		arg.ProductTypeID,
		arg.AttributeID,
		arg.SortOrder,
		arg.VariantOnly,
	)
	return err
}

const listCatalogAttributesByTenantRegion = `-- name: ListCatalogAttributesByTenantRegion :many
SELECT id, tenant_id, region_id, name, slug, input_type, unit, allowed_values, created_at, updated_at
FROM catalog_attributes
WHERE tenant_id = $1 AND region_id = $2
ORDER BY created_at DESC
`

type ListCatalogAttributesByTenantRegionParams struct {
	TenantID string
	RegionID string
}

func (q *Queries) ListCatalogAttributesByTenantRegion(ctx context.Context, arg ListCatalogAttributesByTenantRegionParams) ([]CatalogAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogAttributesByTenantRegion, arg.TenantID, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogAttribute
	for rows.Next() {
		var i CatalogAttribute
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.Name,
			&i.Slug,
			&i.InputType,
			&i.Unit,
			&i.AllowedValues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeValues = `-- name: ListProductAttributeValues :many
SELECT attribute_id, value_text
FROM product_attribute_values
WHERE product_id = $1
ORDER BY attribute_id
`

type ListProductAttributeValuesRow struct {
	AttributeID string
	ValueText   string
}

func (q *Queries) ListProductAttributeValues(ctx context.Context, productID string) ([]ListProductAttributeValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributeValues, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductAttributeValuesRow
	for rows.Next() {
		var i ListProductAttributeValuesRow
		if err := rows.Scan(&i.AttributeID, &i.ValueText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeValuesForProducts = `-- name: ListProductAttributeValuesForProducts :many
SELECT product_id, attribute_id, value_text
FROM product_attribute_values
WHERE product_id = ANY($1::text[])
ORDER BY product_id, attribute_id
`

type ListProductAttributeValuesForProductsRow struct {
	ProductID   string
	AttributeID string
	ValueText   string
}

func (q *Queries) ListProductAttributeValuesForProducts(ctx context.Context, dollar_1 []string) ([]ListProductAttributeValuesForProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributeValuesForProducts, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductAttributeValuesForProductsRow
	for rows.Next() {
		var i ListProductAttributeValuesForProductsRow
		if err := rows.Scan(&i.ProductID, &i.AttributeID, &i.ValueText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTypeAttributeRows = `-- name: ListProductTypeAttributeRows :many
SELECT
  pta.attribute_id,
  pta.sort_order,
  pta.variant_only,
  ca.name AS attribute_name,
  ca.slug AS attribute_slug,
  ca.input_type,
  ca.unit,
  ca.allowed_values
FROM product_type_attributes pta
JOIN catalog_attributes ca ON ca.id = pta.attribute_id
JOIN product_types pt ON pt.id = pta.product_type_id
WHERE pta.product_type_id = $1 AND pt.tenant_id = $2 AND pt.region_id = $3
ORDER BY pta.sort_order ASC, pta.attribute_id ASC
`

type ListProductTypeAttributeRowsParams struct {
	ProductTypeID string
	TenantID      string
	RegionID      string
}

type ListProductTypeAttributeRowsRow struct {
	AttributeID   string
	SortOrder     int32
	VariantOnly   bool
	AttributeName string
	AttributeSlug string
	InputType     string
	Unit          sql.NullString
	AllowedValues pqtype.NullRawMessage
}

func (q *Queries) ListProductTypeAttributeRows(ctx context.Context, arg ListProductTypeAttributeRowsParams) ([]ListProductTypeAttributeRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductTypeAttributeRows, arg.ProductTypeID, arg.TenantID, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductTypeAttributeRowsRow
	for rows.Next() {
		var i ListProductTypeAttributeRowsRow
		if err := rows.Scan(
			&i.AttributeID,
			&i.SortOrder,
			&i.VariantOnly,
			&i.AttributeName,
			&i.AttributeSlug,
			&i.InputType,
			&i.Unit,
			&i.AllowedValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTypesByTenantRegion = `-- name: ListProductTypesByTenantRegion :many
SELECT id, tenant_id, region_id, name, slug, created_at, updated_at
FROM product_types
WHERE tenant_id = $1 AND region_id = $2
ORDER BY created_at DESC
`

type ListProductTypesByTenantRegionParams struct {
	TenantID string
	RegionID string
}

func (q *Queries) ListProductTypesByTenantRegion(ctx context.Context, arg ListProductTypesByTenantRegionParams) ([]ProductType, error) {
	rows, err := q.db.QueryContext(ctx, listProductTypesByTenantRegion, arg.TenantID, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductType
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantAttributeValues = `-- name: ListVariantAttributeValues :many
SELECT attribute_id, value_text
FROM variant_attribute_values
WHERE variant_id = $1
ORDER BY attribute_id
`

type ListVariantAttributeValuesRow struct {
	AttributeID string
	ValueText   string
}

func (q *Queries) ListVariantAttributeValues(ctx context.Context, variantID string) ([]ListVariantAttributeValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariantAttributeValues, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantAttributeValuesRow
	for rows.Next() {
		var i ListVariantAttributeValuesRow
		if err := rows.Scan(&i.AttributeID, &i.ValueText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAttributeFromProductType = `-- name: UnlinkAttributeFromProductType :exec
DELETE FROM product_type_attributes
WHERE product_type_id = $1 AND attribute_id = $2
`

type UnlinkAttributeFromProductTypeParams struct {
	ProductTypeID string
	AttributeID   string
}

func (q *Queries) UnlinkAttributeFromProductType(ctx context.Context, arg UnlinkAttributeFromProductTypeParams) error {
	_, err := q.db.ExecContext(ctx, unlinkAttributeFromProductType, arg.ProductTypeID, arg.AttributeID)
	return err
}

const upsertProductAttributeValue = `-- name: UpsertProductAttributeValue :exec
INSERT INTO product_attribute_values (product_id, attribute_id, value_text, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (product_id, attribute_id) DO UPDATE SET
  value_text = EXCLUDED.value_text,
  updated_at = NOW()
`

type UpsertProductAttributeValueParams struct {
	ProductID   string
	AttributeID string
	ValueText   string
}

func (q *Queries) UpsertProductAttributeValue(ctx context.Context, arg UpsertProductAttributeValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductAttributeValue, arg.ProductID, arg.AttributeID, arg.ValueText)
	return err
}

const upsertVariantAttributeValue = `-- name: UpsertVariantAttributeValue :exec
INSERT INTO variant_attribute_values (variant_id, attribute_id, value_text, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (variant_id, attribute_id) DO UPDATE SET
  value_text = EXCLUDED.value_text,
  updated_at = NOW()
`

type UpsertVariantAttributeValueParams struct {
	VariantID   string
	AttributeID string
	ValueText   string
}

func (q *Queries) UpsertVariantAttributeValue(ctx context.Context, arg UpsertVariantAttributeValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertVariantAttributeValue, arg.VariantID, arg.AttributeID, arg.ValueText)
	return err
}
