// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"
)

const getIdempotencyResource = `-- name: GetIdempotencyResource :one
SELECT resource_id
FROM idempotency_keys
WHERE tenant_id = $1
  AND scope = $2
  AND idempotency_key = $3
`

type GetIdempotencyResourceParams struct {
	TenantID       string
	Scope          string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyResource(ctx context.Context, arg GetIdempotencyResourceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyResource, arg.TenantID, arg.Scope, arg.IdempotencyKey)
	var resource_id string
	err := row.Scan(&resource_id)
	return resource_id, err
}

const insertOrderAudit = `-- name: InsertOrderAudit :exec
INSERT INTO order_status_audit (tenant_id, region_id, order_id, previous_status, new_status, changed_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type InsertOrderAuditParams struct {
	TenantID       string
	RegionID       string
	OrderID        string
	PreviousStatus string
	NewStatus      string
}

func (q *Queries) InsertOrderAudit(ctx context.Context, arg InsertOrderAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertOrderAudit,
		arg.TenantID,
		arg.RegionID,
		arg.OrderID,
		arg.PreviousStatus,
		arg.NewStatus,
	)
	return err
}

const saveIdempotencyResource = `-- name: SaveIdempotencyResource :exec
INSERT INTO idempotency_keys (tenant_id, scope, idempotency_key, resource_id, created_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (tenant_id, scope, idempotency_key) DO NOTHING
`

type SaveIdempotencyResourceParams struct {
	TenantID       string
	Scope          string
	IdempotencyKey string
	ResourceID     string
}

func (q *Queries) SaveIdempotencyResource(ctx context.Context, arg SaveIdempotencyResourceParams) error {
	_, err := q.db.ExecContext(ctx, saveIdempotencyResource,
		arg.TenantID,
		arg.Scope,
		arg.IdempotencyKey,
		arg.ResourceID,
	)
	return err
}
