// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type App struct {
	ID        string
	TenantID  string
	RegionID  string
	Name      string
	IsActive  bool
	AuthToken sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Brand struct {
	ID              string
	TenantID        string
	RegionID        string
	Name            string
	DefaultLocale   string
	DefaultCurrency string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CatalogAttribute struct {
	ID            string
	TenantID      string
	RegionID      string
	Name          string
	Slug          string
	InputType     string
	Unit          sql.NullString
	AllowedValues pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Category struct {
	ID        string
	TenantID  string
	RegionID  string
	Name      string
	Slug      string
	ParentID  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Channel struct {
	ID              string
	TenantID        string
	RegionID        string
	Slug            string
	Name            string
	DefaultCurrency string
	DefaultCountry  string
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Collection struct {
	ID        string
	TenantID  string
	RegionID  string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CollectionProduct struct {
	CollectionID string
	ProductID    string
}

type Customer struct {
	ID        string
	TenantID  string
	RegionID  string
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CustomerAddress struct {
	ID                string
	TenantID          string
	RegionID          string
	CustomerID        string
	IsDefaultShipping bool
	IsDefaultBilling  bool
	FirstName         string
	LastName          string
	Company           sql.NullString
	StreetLine1       string
	StreetLine2       sql.NullString
	City              string
	PostalCode        string
	CountryCode       string
	Phone             sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type EventOutbox struct {
	ID            string
	TenantID      string
	RegionID      string
	EventName     string
	AggregateType string
	AggregateID   string
	Payload       json.RawMessage
	Status        string
	AvailableAt   time.Time
	Attempts      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type IdempotencyKey struct {
	ID             int64
	TenantID       string
	Scope          string
	IdempotencyKey string
	ResourceID     string
	CreatedAt      time.Time
}

type Order struct {
	ID         string
	TenantID   string
	RegionID   string
	CustomerID string
	Status     string
	TotalCents int64
	Currency   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OrderStatusAudit struct {
	ID             int64
	TenantID       string
	RegionID       string
	OrderID        string
	PreviousStatus string
	NewStatus      string
	ChangedAt      time.Time
}

type Payment struct {
	ID                string
	TenantID          string
	RegionID          string
	OrderID           sql.NullString
	CheckoutID        sql.NullString
	Provider          string
	Status            string
	AmountCents       int64
	Currency          string
	ExternalReference sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type PaymentTransaction struct {
	ID              string
	TenantID        string
	RegionID        string
	PaymentID       string
	EventType       string
	AmountCents     int64
	Currency        string
	Success         bool
	RawPayload      json.RawMessage
	ProviderEventID sql.NullString
	CreatedAt       time.Time
}

type PriceBookEntry struct {
	ID          string
	TenantID    string
	RegionID    string
	ProductID   string
	Currency    string
	AmountCents int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Product struct {
	ID                string
	TenantID          string
	RegionID          string
	Sku               string
	Name              string
	Slug              sql.NullString
	Description       sql.NullString
	SeoTitle          sql.NullString
	SeoDescription    sql.NullString
	Metadata          pqtype.NullRawMessage
	ExternalReference sql.NullString
	Currency          string
	PriceCents        int64
	ProductTypeID     sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProductAttributeValue struct {
	ProductID   string
	AttributeID string
	ValueText   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductChannelListing struct {
	ID                string
	TenantID          string
	RegionID          string
	ProductID         string
	ChannelID         string
	IsPublished       bool
	VisibleInListings bool
	PublishedAt       sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProductMedium struct {
	ID        string
	TenantID  string
	RegionID  string
	ProductID string
	Url       string
	MediaType string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProductType struct {
	ID        string
	TenantID  string
	RegionID  string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProductTypeAttribute struct {
	ProductTypeID string
	AttributeID   string
	SortOrder     int32
	VariantOnly   bool
}

type ProductVariant struct {
	ID         string
	TenantID   string
	RegionID   string
	ProductID  string
	Sku        string
	Name       string
	PriceCents int64
	Currency   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Promotion struct {
	ID         string
	TenantID   string
	RegionID   string
	Name       string
	Kind       string
	ValueCents int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Region struct {
	ID         string
	TenantID   string
	RegionID   string
	Name       string
	Currency   string
	LocaleCode string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type StockItem struct {
	ID        string
	TenantID  string
	RegionID  string
	ProductID string
	Quantity  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Translation struct {
	ID           string
	TenantID     string
	RegionID     string
	EntityType   string
	EntityID     string
	LanguageCode string
	Fields       json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type VariantAttributeValue struct {
	VariantID   string
	AttributeID string
	ValueText   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type VariantChannelListing struct {
	ID          string
	TenantID    string
	RegionID    string
	VariantID   string
	ChannelID   string
	Currency    string
	PriceCents  int64
	IsPublished bool
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WebhookDelivery struct {
	ID             string
	TenantID       string
	RegionID       string
	OutboxID       string
	SubscriptionID string
	Status         string
	ResponseStatus sql.NullInt64
	ResponseBody   sql.NullString
	Attempts       int64
	NextRetryAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WebhookEndpoint struct {
	ID          int64
	TenantID    string
	RegionID    string
	EventName   string
	EndpointUrl string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WebhookReplayAudit struct {
	ID          string
	TenantID    string
	RegionID    string
	OutboxID    string
	Reason      string
	RequestedBy sql.NullString
	CreatedAt   time.Time
}

type WebhookSubscription struct {
	ID          string
	TenantID    string
	RegionID    string
	AppID       sql.NullString
	EventName   string
	EndpointUrl string
	Secret      sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
