// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Brand struct {
	ID              string
	TenantID        string
	RegionID        string
	Name            string
	DefaultLocale   string
	DefaultCurrency string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Category struct {
	ID        string
	TenantID  string
	RegionID  string
	Name      string
	Slug      string
	ParentID  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Collection struct {
	ID        string
	TenantID  string
	RegionID  string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CollectionProduct struct {
	CollectionID string
	ProductID    string
}

type Customer struct {
	ID        string
	TenantID  string
	RegionID  string
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type IdempotencyKey struct {
	ID             int64
	TenantID       string
	Scope          string
	IdempotencyKey string
	ResourceID     string
	CreatedAt      time.Time
}

type Order struct {
	ID         string
	TenantID   string
	RegionID   string
	CustomerID string
	Status     string
	TotalCents int64
	Currency   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OrderStatusAudit struct {
	ID             int64
	TenantID       string
	RegionID       string
	OrderID        string
	PreviousStatus string
	NewStatus      string
	ChangedAt      time.Time
}

type PriceBookEntry struct {
	ID          string
	TenantID    string
	RegionID    string
	ProductID   string
	Currency    string
	AmountCents int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Product struct {
	ID         string
	TenantID   string
	RegionID   string
	Sku        string
	Name       string
	Currency   string
	PriceCents int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ProductMedium struct {
	ID        string
	TenantID  string
	RegionID  string
	ProductID string
	Url       string
	MediaType string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProductVariant struct {
	ID         string
	TenantID   string
	RegionID   string
	ProductID  string
	Sku        string
	Name       string
	PriceCents int64
	Currency   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Promotion struct {
	ID         string
	TenantID   string
	RegionID   string
	Name       string
	Kind       string
	ValueCents int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Region struct {
	ID         string
	TenantID   string
	RegionID   string
	Name       string
	Currency   string
	LocaleCode string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type StockItem struct {
	ID        string
	TenantID  string
	RegionID  string
	ProductID string
	Quantity  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WebhookEndpoint struct {
	ID          int64
	TenantID    string
	RegionID    string
	EventName   string
	EndpointUrl string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
