// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, tenant_id, region_id, customer_id, status, total_cents, currency, created_at, updated_at
FROM orders
WHERE id = $1 AND tenant_id = $2
`

type GetOrderByIDParams struct {
	ID       string
	TenantID string
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, arg.ID, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.CustomerID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
  id, tenant_id, region_id, customer_id, status, total_cents, currency, created_at, updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, tenant_id, region_id, customer_id, status, total_cents, currency, created_at, updated_at
`

type InsertOrderParams struct {
	ID         string
	TenantID   string
	RegionID   string
	CustomerID string
	Status     string
	TotalCents int64
	Currency   string
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, insertOrder,
		arg.ID,
		arg.TenantID,
		arg.RegionID,
		arg.CustomerID,
		arg.Status,
		arg.TotalCents,
		arg.Currency,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.CustomerID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByTenantRegion = `-- name: ListOrdersByTenantRegion :many
SELECT id, tenant_id, region_id, customer_id, status, total_cents, currency, created_at, updated_at
FROM orders
WHERE tenant_id = $1
  AND ($2::text = '' OR region_id = $2)
  AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListOrdersByTenantRegionParams struct {
	TenantID string
	Column2  string
	Column3  time.Time
	Limit    int32
}

func (q *Queries) ListOrdersByTenantRegion(ctx context.Context, arg ListOrdersByTenantRegionParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByTenantRegion,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RegionID,
			&i.CustomerID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND updated_at = $4
RETURNING id, tenant_id, region_id, customer_id, status, total_cents, currency, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID        string
	TenantID  string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RegionID,
		&i.CustomerID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
